use std::collections::HashSet;

use crate::db::DbType;

use super::{QueryCompletion, QueryCompletionKind};

const COMMON_KEYWORDS: &str = "SELECT FROM WHERE AND OR NOT NULL IS IN LIKE BETWEEN ORDER BY GROUP HAVING LIMIT OFFSET AS DISTINCT ALL ANY SOME JOIN INNER LEFT RIGHT FULL OUTER ON USING CROSS UNION INTERSECT EXCEPT WITH RECURSIVE INSERT INTO VALUES UPDATE SET DELETE CREATE TABLE VIEW INDEX DATABASE SCHEMA IF EXISTS ALTER ADD DROP COLUMN CONSTRAINT PRIMARY KEY FOREIGN REFERENCES UNIQUE CHECK DEFAULT AUTO_INCREMENT IDENTITY BEGIN COMMIT ROLLBACK TRANSACTION SAVEPOINT START CASE WHEN THEN ELSE END IIF TRUE FALSE CAST CONVERT INT INTEGER BIGINT SMALLINT TINYINT DECIMAL NUMERIC FLOAT DOUBLE REAL CHAR VARCHAR TEXT BLOB DATE TIME DATETIME TIMESTAMP BOOLEAN ASC DESC EXPLAIN ANALYZE";
const COMMON_FUNCTIONS: &str = "COUNT SUM AVG MIN MAX CONCAT SUBSTRING SUBSTR LENGTH LOWER UPPER TRIM LTRIM RTRIM REPLACE POSITION INSTR REVERSE LEFT RIGHT REPEAT ABS CEIL CEILING FLOOR ROUND TRUNC POWER SQRT MOD RANDOM RAND GREATEST LEAST SIGN EXP LOG LN NOW CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP EXTRACT COALESCE NULLIF IFNULL ISNULL";

const MYSQL_KEYWORDS: &str = "SHOW DATABASES TABLES DESCRIBE USE ENGINE CHARSET COLLATE REGEXP BINARY UNSIGNED ZEROFILL ENUM MEDIUMINT TINYTEXT MEDIUMTEXT LONGTEXT TINYBLOB MEDIUMBLOB LONGBLOB JSON YEAR STRAIGHT_JOIN LOCK UNLOCK OPTIMIZE";
const MYSQL_FUNCTIONS: &str = "NOW CURDATE CURTIME DATE_FORMAT STR_TO_DATE DATE_ADD DATE_SUB DATEDIFF TIMESTAMPDIFF TIMESTAMPADD UNIX_TIMESTAMP FROM_UNIXTIME YEAR MONTH DAY HOUR MINUTE SECOND DAYNAME MONTHNAME WEEK WEEKDAY QUARTER CONCAT_WS GROUP_CONCAT FIELD FIND_IN_SET LOCATE CHAR_LENGTH CHARACTER_LENGTH LPAD RPAD SPACE LCASE UCASE INSERT ELT EXPORT_SET MAKE_SET OCT IF IFNULL NULLIF CASE JSON_OBJECT JSON_ARRAY JSON_EXTRACT JSON_KEYS JSON_LENGTH JSON_VALID JSON_CONTAINS JSON_SET JSON_INSERT JSON_REPLACE JSON_REMOVE JSON_MERGE LAST_INSERT_ID ROW_COUNT CONNECTION_ID DATABASE USER VERSION MD5 SHA1 SHA2 PASSWORD AES_ENCRYPT AES_DECRYPT UUID";

const POSTGRES_KEYWORDS: &str = "RETURNING ILIKE SIMILAR ARRAY JSONB HSTORE SERIAL BIGSERIAL SMALLSERIAL BYTEA UUID INET CIDR MACADDR MONEY INTERVAL TSQUERY TSVECTOR REGCLASS LATERAL MATERIALIZED REFRESH EXTENSION CONCURRENTLY VACUUM REINDEX CLUSTER NOTIFY LISTEN UNLISTEN COPY EXCLUDE PARTITION INHERIT RULE WINDOW OVER OVERLAPS";
const POSTGRES_FUNCTIONS: &str = "NOW CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP AGE DATE_PART DATE_TRUNC TO_CHAR TO_DATE TO_TIMESTAMP TO_NUMBER EXTRACT JUSTIFY_DAYS JUSTIFY_HOURS CONCAT CONCAT_WS STRING_AGG ARRAY_AGG ARRAY_LENGTH ARRAY_APPEND ARRAY_PREPEND ARRAY_CAT ARRAY_REMOVE ARRAY_REPLACE UNNEST GENERATE_SERIES JSONB_BUILD_OBJECT JSONB_BUILD_ARRAY JSONB_AGG JSONB_OBJECT_AGG JSONB_ARRAY_ELEMENTS JSONB_ARRAY_ELEMENTS_TEXT JSONB_OBJECT_KEYS JSONB_PATH_EXISTS JSONB_PATH_QUERY JSON_BUILD_OBJECT JSON_BUILD_ARRAY JSON_AGG COALESCE NULLIF GREATEST LEAST LENGTH CHAR_LENGTH OCTET_LENGTH SUBSTRING LOWER UPPER INITCAP LPAD RPAD TRIM LTRIM RTRIM REPLACE TRANSLATE OVERLAY POSITION REGEXP_MATCH REGEXP_MATCHES REGEXP_REPLACE REGEXP_SPLIT_TO_ARRAY REGEXP_SPLIT_TO_TABLE GEN_RANDOM_UUID UUID_GENERATE_V4 MD5 CRYPT ROW_NUMBER RANK DENSE_RANK LAG LEAD FIRST_VALUE LAST_VALUE NTILE PG_TYPEOF PG_TABLE_SIZE PG_DATABASE_SIZE CURRENT_USER SESSION_USER CURRENT_DATABASE";

const SQLITE_KEYWORDS: &str = "PRAGMA AUTOINCREMENT GLOB VACUUM ATTACH DETACH REINDEX INDEXED CONFLICT ABORT FAIL IGNORE REPLACE DEFERRED IMMEDIATE EXCLUSIVE TEMP WITHOUT ROWID";
const SQLITE_FUNCTIONS: &str = "DATE TIME DATETIME JULIANDAY STRFTIME UNIXEPOCH TYPEOF PRINTF FORMAT QUOTE HEX RANDOM RANDOMBLOB IFNULL NULLIF COALESCE IIF GROUP_CONCAT TOTAL INSTR CHANGES TOTAL_CHANGES LAST_INSERT_ROWID JSON JSON_ARRAY JSON_OBJECT JSON_EXTRACT JSON_TYPE JSON_VALID JSON_ARRAY_LENGTH JSON_INSERT JSON_REPLACE JSON_SET JSON_REMOVE";

const SQLSERVER_KEYWORDS: &str = "TOP NOLOCK IDENTITY NVARCHAR NCHAR NTEXT UNIQUEIDENTIFIER BIT MONEY SMALLMONEY IMAGE DATETIMEOFFSET DATETIME2 SMALLDATETIME HIERARCHYID SQL_VARIANT XML GEOGRAPHY GEOMETRY ROWGUIDCOL MERGE OUTPUT APPLY PIVOT UNPIVOT TRY CATCH THROW RAISERROR PRINT EXEC EXECUTE PROC PROCEDURE TRIGGER CURSOR FETCH OPEN CLOSE DEALLOCATE GO OFFSET ROWS NEXT ONLY";
const SQLSERVER_FUNCTIONS: &str = "GETDATE GETUTCDATE SYSDATETIME SYSDATETIMEOFFSET SYSUTCDATETIME DATEADD DATEDIFF DATEPART DATENAME DAY MONTH YEAR EOMONTH CONVERT CAST TRY_CAST TRY_CONVERT TRY_PARSE PARSE LEN DATALENGTH CHARINDEX PATINDEX SUBSTRING STUFF STRING_AGG STRING_SPLIT CONCAT CONCAT_WS FORMAT QUOTENAME REVERSE REPLICATE SPACE UPPER LOWER LTRIM RTRIM TRIM REPLACE ISNULL NULLIF COALESCE IIF CHOOSE NEWID NEWSEQUENTIALID HASHBYTES CHECKSUM ROW_NUMBER RANK DENSE_RANK NTILE LAG LEAD FIRST_VALUE LAST_VALUE OBJECT_ID OBJECT_NAME DB_NAME DB_ID USER_NAME SUSER_NAME SCHEMA_NAME @@ROWCOUNT @@IDENTITY @@VERSION @@SERVERNAME @@SPID";

const CLICKHOUSE_KEYWORDS: &str = "PREWHERE FORMAT ENGINE MERGETREE REPLACINGMERGETREE AGGREGATINGMERGETREE SUMMINGMERGETREE COLLAPSINGMERGETREE PARTITION SAMPLE FINAL TTL CODEC LOWCARDINALITY NULLABLE ARRAY TUPLE MAP NESTED MATERIALIZED ALIAS SETTINGS CLUSTER DICTIONARY OPTIMIZE SYSTEM KILL SHOW DESCRIBE LIMIT BY TOTALS";
const CLICKHOUSE_FUNCTIONS: &str = "COUNT COUNTIF SUMIF AVGIF UNIQ UNIQEXACT GROUPARRAY GROUPUNIQARRAY ARGMIN ARGMAX QUANTILE QUANTILEEXACT TOPK ANY ANYLAST TODATE TODATETIME TODATETIME64 TOSTARTOFHOUR TOSTARTOFDAY TOSTARTOFMONTH DATEADD DATEDIFF FORMATDATETIME PARSEDATETIMEBESTEFFORT NOW64 ARRAYMAP ARRAYFILTER ARRAYJOIN ARRAYEXISTS ARRAYREDUCE HAS HASANY TYPENAME TOSTRING TOINT64 TOUINT64 TOFLOAT64 TODECIMAL64 JSONEXTRACT JSONEXTRACTSTRING JSONEXTRACTINT SIMPLEJSONEXTRACTSTRING CITYHASH64 SIPHASH64 GENERATEUUIDV4 MULTIIF ASSUMENOTNULL";

pub(super) fn completions(db_type: DbType) -> Vec<QueryCompletion> {
    let (keywords, functions, dialect) = match db_type {
        DbType::MySQL => (MYSQL_KEYWORDS, MYSQL_FUNCTIONS, "MYSQL"),
        DbType::PostgreSQL => (POSTGRES_KEYWORDS, POSTGRES_FUNCTIONS, "POSTGRESQL"),
        DbType::SQLite => (SQLITE_KEYWORDS, SQLITE_FUNCTIONS, "SQLITE"),
        DbType::SQLServer => (SQLSERVER_KEYWORDS, SQLSERVER_FUNCTIONS, "SQLSERVER"),
        DbType::ClickHouse => (CLICKHOUSE_KEYWORDS, CLICKHOUSE_FUNCTIONS, "CLICKHOUSE"),
        DbType::MongoDB | DbType::Redis => return Vec::new(),
    };
    let mut seen_keywords = HashSet::new();
    let keywords = COMMON_KEYWORDS
        .split_ascii_whitespace()
        .chain(keywords.split_ascii_whitespace())
        .filter(|keyword| seen_keywords.insert(*keyword))
        .map(|keyword| QueryCompletion {
            label: keyword.to_string(),
            new_text: keyword.to_string(),
            detail: format!("{dialect} keyword"),
            kind: QueryCompletionKind::Keyword,
        })
        .collect::<Vec<_>>();
    let mut seen_functions = HashSet::new();
    let functions = COMMON_FUNCTIONS
        .split_ascii_whitespace()
        .chain(functions.split_ascii_whitespace())
        .filter(|function| seen_functions.insert(*function))
        .map(|function| QueryCompletion {
            label: function.to_string(),
            new_text: format!("{function}()"),
            detail: format!("{dialect} function"),
            kind: QueryCompletionKind::Function,
        });
    keywords.into_iter().chain(functions).collect()
}
